matrix:
  include:
  - language: ruby
    name: Github Linguist (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/github-linguist
    install:
    - "./github-linguist/install.sh"
    script:
    - "./github-linguist/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 2.7)
    rvm: 2.7
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: cyHGUz/uIDDLa9bW6a9NsgGSszCM8rQmOEaOYS2jRiLNHaprqW+oaL6T2YlbGH9fqtF5gVnLj+p4qWtArRkSrtwUnz0wmDrCMV1t2kVk3gNwVTMduq0A87GpyA9aeOGZkr6xK5ROqQoq0T4Ya7li7J9JJVugTABMmEmKi3ilcEEGdn5Lq82tbs6aI2CsTYwfTc8/myDVjaCKcnfqgGFbfoZtAG6Q1xzKL61J0IZ9gFb3OzRnABuofvHmxWuiH1zOCGM5xeroRBjTrJ3N5OLySAIa2GrpHxXuQoWv+tjdhAj1TjTrj9fA82vObdX4dfxnfl5XoDc9sUqIl21ZzEUH/MBc+AExN64hkSTMI+AK7bjNbkIePr5JVSRzLvkyifW8pe9pYjbHHin7VFR9sMT/+neq7JhZcnGbsrM3g8ixzLL/sSUDAT6SUxjXzbffVeWko9xdpNZPa29D3svpnPPKdZIrBOadLF1ulpGu7g2849ROSqVIf8qiRtyzVFc/jG2LJQnOKguMp7s9AIO7y7o7WsQfAYrnP2XuAlT+dx8LtfEU3fEHqJtF6Q4YXUFpkK+MIgzDR/5ofrftg2jBnBcyWr8Qw1w1DgEdCNmVje5FbG3JudDFdGp9BTZp8twrQ+rVk2JK6oweCX5MO+AIJ6bFYNZi6cKFAc3vk1/cnvaFTFE=
