matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: cQ327VHlwosma8eRqnx/mS+gSUOQQug5+1nUwAzJb01bZcaiJfS8HityVeyeexXQCw0ZVzuIbOQf+tCUiuPeOfLXLQEJ3VHU/sjFJXZIq4yiER5QQONaYs7iGzo011lKN6+M5Py4+Af2OuH06yrMSsiVrLAEFbMaXL/YEaMNfFY0UnTTxpmXdmsKUVuDbFGbL6b864oPHDYUJkLBeBJ4lYIbc7f5GwFqaHCoF7vG7JN555g4WiAHIAgaVpkrAgXj0xF6XBygTqDcshzNWaWCB4Gz/kjMNj5ZkJaVBXk/M4YyllD1CaGCW8/hXaxnp4+dDZrZqtmxAOG4v6XIdT1P/T1KyiG7hUn02P5SplEpg3rifXzfIy7qpkCjRlkVzxSe6lXWaMp3MZ5c7i0C47IDBs+GqHujqvm5/AoFJAoYA4Bk1b9mm7UbfjT8sd4fb9hwv8W1lhACbJJTvJsxigl67d/PqOR0LntB43mqKl5A6W/FMwVLDoxFVYsYGeD0fbE/ec2C3NqgfSRCorgHQczHUvmfa6aKUhlQZF8Fe5OaJcXxaDuhJyCFU7xC+iC5xyG5gJEhont614VAfrbzR4tqGq/6+No6KVuUM4uH6hwxFtmDcxHX/wVX3IqWx9Bpcg1Jl5L0DOxLT2533ZreRW7w2MHatPUHygFc1N//czV9aRM=
