matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: mMuU2WVJis8oWdSwakBElAmegEWu3zXhYWCTQsYlTnOUnrYcuzzHZGlj2OJTSlVRSdaDyrbuhjjnAPPA73rmebhO0AeY6/KoeV3nFIJ8bbIvsp/yDZQ7FUVFYO6J4+eosSkzQ3+mSmzSwc1zMaZ/N75LZrB3dxOhNzWAzS/ZWs8VZVnf7lUjM07Tn93a3/aWKW5LijHBAZUa7M7DI7wkIaoA2DiDXGpAZjObKX9aavBWzkQQwBOLXv9ArcL/vDH5ln2MSzllRK3H4jZDWGAncYlhnarBt3s3xLJRq1OxmNeB7k+NYm1Sath96Y2b1Fom76S3K0bEz9Iu7DWlyTwCKCXJzB4UOX4y3dpsW5qnknWvmxp4SpDR2/CjaCPYHZbEtbPhH2QbWAh9bMVKv/eHtNPWByciVcMdF4o2Qv4y/NkI3LdCYF+fD3aIiNn/al2eRABKMwyJbyGQwfxEIF4K3xKRcl/3oOCSnuWzMvsN673ottmPdYfM3dRfIQBqrl51c/1jTQLlrwi2zus6EmAcErLBSHQU7KjSGG5rCnE9DhuGCKipS8JDnTcskNzCEsyRCHy9fWLOh6BNZKre05akX9lYC4xBojMTxnYZGzg/wwR9dQ1SzXCZHSlApI0UQ56O1ULeB4t/VTYLAtWx7vx+maAQ1sm+yhlpaiABimIwqcc=
